'use strict';
// The four standalone issue pages: /read/issue-1 … /read/issue-4.
// These are generated by tools/build_pages.py from index.html, so this suite
// is really asking two things — did the generator produce a correct page, and
// does script.js still work against a DOM that holds one issue instead of four.

const { newPage, watchErrors, watchBadRequests, Results } = require('./lib/harness');

module.exports = async function issuePages(ctx, base) {
  const r = new Results();
  const handoffs = {};
  const chapters = {};
  const titles = {};

  for (const n of [1, 2, 3, 4]) {
    const page = await newPage(ctx);
    const errors = watchErrors(page);
    const bad = watchBadRequests(page, base);
    await page.goto(`${base}/read/issue-${n}`, { waitUntil: 'networkidle' });

    r.ok(`i${n}: no failed same-origin requests`, bad.length === 0, bad.slice(0, 5).join(' | '));
    r.ok(`i${n}: no JS errors`, errors.length === 0, errors.slice(0, 3).join(' | '));

    // ── this page's identity is its own, not the home page's
    const meta = await page.evaluate(() => ({
      title: document.title,
      desc: document.querySelector('meta[name=description]')?.content || '',
      canonical: document.querySelector('link[rel=canonical]')?.href || '',
      ogImage: document.querySelector('meta[property="og:image"]')?.content || '',
      ogTitle: document.querySelector('meta[property="og:title"]')?.content || '',
      ogType: document.querySelector('meta[property="og:type"]')?.content || '',
      twImage: document.querySelector('meta[name="twitter:image"]')?.content || '',
      prev: document.querySelector('link[rel=prev]')?.href || '',
      next: document.querySelector('link[rel=next]')?.href || '',
      ld: document.querySelector('script[type="application/ld+json"]')?.textContent || '',
    }));
    r.ok(`i${n}: <title> names this issue`, meta.title.includes(`Issue #0${n}`), meta.title);
    r.ok(`i${n}: description is issue-specific`,
      meta.desc.includes(`Issue #0${n}`) && meta.desc.length > 80, meta.desc.slice(0, 70));
    r.ok(`i${n}: canonical points here`, meta.canonical.endsWith(`/read/issue-${n}`), meta.canonical);
    r.ok(`i${n}: og:image is this issue's cover`,
      meta.ogImage.endsWith(`cover-issue${n}.webp`), meta.ogImage);
    r.ok(`i${n}: twitter:image matches og:image`, meta.twImage === meta.ogImage);
    r.ok(`i${n}: og:title names this issue`, meta.ogTitle.includes(`#0${n}`), meta.ogTitle);
    r.ok(`i${n}: og:type is article`, meta.ogType === 'article', meta.ogType);
    r.ok(`i${n}: rel=prev`, n === 1 ? !meta.prev : meta.prev.endsWith(`issue-${n - 1}`), meta.prev);
    r.ok(`i${n}: rel=next`, n === 4 ? !meta.next : meta.next.endsWith(`issue-${n + 1}`), meta.next);

    let ld = null;
    try { ld = JSON.parse(meta.ld); } catch (e) { /* asserted next */ }
    r.ok(`i${n}: JSON-LD parses`, !!ld);
    if (ld) {
      const graph = ld['@graph'] || [];
      const issue = graph.find(g => g['@type'] === 'ComicIssue');
      const wp = graph.find(g => g['@type'] === 'WebPage');
      r.ok(`i${n}: has a ComicIssue node`, !!issue);
      r.ok(`i${n}: issueNumber is ${n}`, issue && issue.issueNumber === n, issue && String(issue.issueNumber));
      r.ok(`i${n}: has a publication date`,
        issue && /^\d{4}-\d{2}-\d{2}$/.test(issue.datePublished || ''), issue && issue.datePublished);
      r.ok(`i${n}: chapters are indexed`,
        issue && Array.isArray(issue.hasPart) && issue.hasPart.length >= 3,
        issue && String((issue.hasPart || []).length));
      r.ok(`i${n}: breadcrumb has three steps`, wp && wp.breadcrumb?.itemListElement?.length === 3);
      r.ok(`i${n}: declared part of the series`,
        issue && String(issue.isPartOf?.['@id'] || '').includes('#comicseries'));
    }

    // ── the story is actually on the page
    const dom = await page.evaluate(() => {
      const panel = document.querySelector('.issue-reader-panel');
      return {
        panels: document.querySelectorAll('.issue-reader-panel').length,
        panelId: panel?.id,
        active: !!panel?.classList.contains('active'),
        visible: panel ? getComputedStyle(panel).display !== 'none' : false,
        pages: document.querySelectorAll('.issue-reader-panel .reader-page').length,
        prose: document.querySelectorAll('.story-prose').length,
        tabs: document.querySelectorAll('.issue-page-tab').length,
        activeTab: document.querySelector('.issue-page-tab.active')?.textContent.trim(),
        crumbs: document.querySelectorAll('.issue-crumbs li').length,
        chapters: document.querySelectorAll('.chapter-title').length,
        permalink: document.querySelectorAll('.reader-permalink').length,
      };
    });
    r.ok(`i${n}: exactly one reader panel`, dom.panels === 1, String(dom.panels));
    r.ok(`i${n}: it is panel-i${n}`, dom.panelId === `panel-i${n}`, dom.panelId);
    r.ok(`i${n}: panel is active and visible`, dom.active && dom.visible);
    r.ok(`i${n}: story pages rendered`, dom.pages >= 3, String(dom.pages));
    r.ok(`i${n}: prose rendered`, dom.prose >= 5, String(dom.prose));
    r.ok(`i${n}: four issues in the tab bar`, dom.tabs === 4, String(dom.tabs));
    r.ok(`i${n}: this issue's tab is current`, dom.activeTab === `Issue #0${n}`, dom.activeTab);
    r.ok(`i${n}: breadcrumb present`, dom.crumbs === 3, String(dom.crumbs));
    chapters[n] = dom.chapters;
    // "Issue #02: Ṣàngó's Daughter — Catalyst…" → the title alone.
    titles[n] = (meta.title.split(': ')[1] || '').split(' — ')[0];
    handoffs[n] = await page.evaluate(() => {
      const aside = document.querySelector('.issue-handoff');
      if (!aside) return null;
      const card = aside.querySelector('.handoff-card');
      const img = aside.querySelector('img.handoff-cover');
      return {
        cards: document.querySelectorAll('.handoff-card').length,
        href: card?.getAttribute('href') || '',
        name: aside.querySelector('.handoff-name')?.textContent.trim() || '',
        blurb: (aside.querySelector('.handoff-blurb')?.textContent || '').trim(),
        cta: aside.querySelector('.handoff-cta')?.textContent.trim() || '',
        facts: [...aside.querySelectorAll('.handoff-facts span')].map(s => s.textContent.trim()),
        cover: img?.getAttribute('src') || '',
        back: aside.querySelector('.handoff-back')?.getAttribute('href') || '',
        all: aside.querySelector('.handoff-all')?.getAttribute('href') || '',
        // The whole card is one link. Anything focusable inside it would be
        // unreachable markup a keyboard user can still land on.
        nested: card ? card.querySelectorAll('a, button, [tabindex]').length : -1,
        labelled: aside.getAttribute('aria-labelledby') === 'handoff-title' &&
                  !!aside.querySelector('#handoff-title'),
      };
    });
    const h = handoffs[n];
    r.ok(`i${n}: the story hands off at the end`, !!h && h.cards === 1, JSON.stringify(h && h.cards));
    if (h) {
      const target = n < 4 ? `./issue-${n + 1}` : '/#access';
      r.ok(`i${n}: the hand-off points at ${target}`, h.href === target, h.href);
      r.ok(`i${n}: it names what comes next`, h.name.length > 3, h.name);
      r.ok(`i${n}: it says what happens in it`, h.blurb.length > 60, String(h.blurb.length));
      r.ok(`i${n}: it carries three facts`, h.facts.length === 3, h.facts.join(' / '));
      r.ok(`i${n}: the call to action is explicit`, /^(Read|See)\b/.test(h.cta), h.cta);
      r.ok(`i${n}: the card is a single link`, h.nested === 0, String(h.nested));
      r.ok(`i${n}: the card is labelled for screen readers`, h.labelled === true);
      r.ok(`i${n}: links back to every issue`, h.all === '/#read', h.all);
      r.ok(`i${n}: ${n > 1 ? 'links back to the previous issue' : 'has no previous issue to link'}`,
        n > 1 ? h.back === `./issue-${n - 1}` : h.back === '', h.back);
      if (n < 4) {
        r.ok(`i${n}: shows the cover of Issue #0${n + 1}`,
          h.cover.endsWith(`cover-issue${n + 1}.webp`), h.cover);
        // The cover is loading="lazy" and the card sits at the foot of a long
        // page, so at load it is correctly still unfetched. Scrolling to it is
        // what a reader does, and only then is "does it load" a real question.
        const cover = await page.evaluate(async () => {
          const img = document.querySelector('img.handoff-cover');
          img.scrollIntoView({ block: 'center' });
          if (!img.complete) {
            await new Promise(done => {
              img.addEventListener('load', done, { once: true });
              img.addEventListener('error', done, { once: true });
              setTimeout(done, 5000);
            });
          }
          return {
            loaded: img.complete && img.naturalWidth > 0,
            // A card that reserves the wrong box shifts the page as it loads.
            ratioOK: Math.abs((img.getAttribute('width') / img.getAttribute('height')) -
                              (img.naturalWidth / img.naturalHeight)) < 0.01,
            declared: `${img.getAttribute('width')}x${img.getAttribute('height')}`,
            natural: `${img.naturalWidth}x${img.naturalHeight}`,
          };
        });
        r.ok(`i${n}: that cover actually loads once scrolled to`,
          cover.loaded === true, JSON.stringify(cover));
        r.ok(`i${n}: the cover reserves its true aspect ratio`,
          cover.ratioOK === true, `${cover.declared} declared vs ${cover.natural} natural`);
      }
    }
    r.ok(`i${n}: no link to the page you are on`, dom.permalink === 0, String(dom.permalink));

    // ── shared chrome survived the slice
    const chrome = await page.evaluate(() => ({
      nav: !!document.querySelector('nav .nav-links'),
      mobileNav: !!document.getElementById('mobileNav'),
      footer: !!document.querySelector('footer'),
      cmdk: !!document.getElementById('cmdk'),
      notes: !!document.getElementById('fnBar') && !!document.getElementById('fnDrawer'),
      kb: !!document.getElementById('kb-panel'),
      glPop: !!document.getElementById('glPop'),
      skip: document.querySelector('.skip-link')?.getAttribute('href'),
      navHashes: [...document.querySelectorAll('nav a[href^="#"]')].map(a => a.getAttribute('href')),
      issueLinks: [...document.querySelectorAll('footer a[href*="/read/issue-"]')].length,
    }));
    r.ok(`i${n}: nav present`, chrome.nav);
    r.ok(`i${n}: mobile nav present`, chrome.mobileNav);
    r.ok(`i${n}: footer present`, chrome.footer);
    r.ok(`i${n}: search palette present`, chrome.cmdk);
    r.ok(`i${n}: field notes present`, chrome.notes);
    r.ok(`i${n}: keyboard help present`, chrome.kb);
    r.ok(`i${n}: glossary popover present`, chrome.glPop);
    r.ok(`i${n}: skip link targets the story`, chrome.skip === '#read', chrome.skip);
    // Only #read is on this page; every other nav fragment must go home.
    r.ok(`i${n}: nav fragments retargeted home`,
      chrome.navHashes.every(h => h === '#read'), chrome.navHashes.join(','));
    r.ok(`i${n}: footer lists all four issues`, chrome.issueLinks === 4, String(chrome.issueLinks));

    // ── JS modules initialised against a one-panel DOM
    const js = await page.evaluate(() => ({
      flag: window.CATALYST_PAGE,
      search: typeof window.CatalystSearch?.open === 'function',
      notes: typeof window.CatalystFieldNotes?.open === 'function',
      trap: typeof window.CatalystFocusTrap?.anyOpen === 'function',
      jump: typeof window.catalystJumpTo === 'function',
    }));
    r.ok(`i${n}: recognised as issue page ${n}`,
      js.flag?.issuePage === true && js.flag?.issue === n, JSON.stringify(js.flag));
    r.ok(`i${n}: search module live`, js.search);
    r.ok(`i${n}: field notes module live`, js.notes);
    r.ok(`i${n}: focus trap live`, js.trap);
    r.ok(`i${n}: jump API live`, js.jump);

    // ── search still reaches the rest of the site from here
    await page.keyboard.press('Control+k');
    await page.waitForTimeout(350);
    r.ok(`i${n}: Ctrl/Cmd-K opens search`,
      await page.evaluate(() => document.getElementById('cmdk')?.classList.contains('open')) === true);
    await page.fill('#cmdkInput', 'heroes');
    await page.waitForTimeout(300);
    const homeHits = await page.evaluate(() =>
      [...document.querySelectorAll('.cmdk-row')].map(e => e.textContent).join(' | '));
    r.ok(`i${n}: home-page sections are searchable`, /Heroes/i.test(homeHits), homeHits.slice(0, 90));
    await page.fill('#cmdkInput', 'issue');
    await page.waitForTimeout(300);
    const issueHits = await page.evaluate(() =>
      [...document.querySelectorAll('.cmdk-row')].map(e => e.textContent.trim()));
    r.ok(`i${n}: sibling issues are searchable`,
      issueHits.some(t => /Issue #0[1-4]/.test(t)), issueHits.slice(0, 3).join(' | '));
    await page.keyboard.press('Escape');
    await page.close();
  }

  // ── moving between pages
  const page = await newPage(ctx);

  await page.goto(`${base}/read/issue-2`, { waitUntil: 'networkidle' });
  await page.click('.issue-page-tab:not(.active)');
  await page.waitForLoadState('networkidle');
  r.ok('tab bar navigates to another issue page', /issue-[134]/.test(page.url()), page.url());

  // ── a hand-off card makes a factual claim about a page the reader has not
  //    opened yet. Checking it against that page is the only way to know the
  //    card is not quietly lying: a generator bug that read the wrong panel
  //    would still produce a card that looks completely correct.
  for (const n of [1, 2, 3]) {
    const h = handoffs[n];
    if (!h) continue;
    const claimed = parseInt((h.facts.find(f => /chapter/i.test(f)) || '').match(/\d+/)?.[0], 10);
    r.ok(`i${n}: the chapter count it promises is the one Issue #0${n + 1} has`,
      claimed === chapters[n + 1], `${claimed} claimed vs ${chapters[n + 1]} actual`);
    r.ok(`i${n}: the title it promises is the one Issue #0${n + 1} carries`,
      h.name === titles[n + 1], `"${h.name}" promised vs "${titles[n + 1]}" actual`);
  }

  // A short deep link on the page it belongs to
  await page.goto(`${base}/read/issue-3#p2`, { waitUntil: 'networkidle' });
  await page.waitForFunction(() => {
    const ps = [...document.querySelectorAll('.issue-reader-panel .reader-page')];
    return ps.findIndex(p => getComputedStyle(p).display !== 'none') === 2;
  }, null, { timeout: 5000 }).catch(() => {});
  const onPage2 = await page.evaluate(() => {
    const ps = [...document.querySelectorAll('.issue-reader-panel .reader-page')];
    return ps.findIndex(p => getComputedStyle(p).display !== 'none');
  });
  r.ok('#p2 opens page 2 of that issue', onPage2 === 2, String(onPage2));

  // A shared link for a different issue must land on the right page, not break
  await page.goto(`${base}/read/issue-1#read-i4-p1`, { waitUntil: 'networkidle' });
  await page.waitForURL(/issue-4/, { timeout: 5000 }).catch(() => {});
  r.ok('a deep link for another issue redirects to it', /issue-4/.test(page.url()), page.url());

  await page.close();
  return r;
};
