'use strict';
// The four standalone issue pages: /read/issue-1 … /read/issue-4.
// These are generated by tools/build_pages.py from index.html, so this suite
// is really asking two things — did the generator produce a correct page, and
// does script.js still work against a DOM that holds one issue instead of four.

const { newPage, watchErrors, watchBadRequests, Results } = require('./lib/harness');

module.exports = async function issuePages(ctx, base) {
  const r = new Results();

  for (const n of [1, 2, 3, 4]) {
    const page = await newPage(ctx);
    const errors = watchErrors(page);
    const bad = watchBadRequests(page, base);
    await page.goto(`${base}/read/issue-${n}`, { waitUntil: 'networkidle' });

    r.ok(`i${n}: no failed same-origin requests`, bad.length === 0, bad.slice(0, 5).join(' | '));
    r.ok(`i${n}: no JS errors`, errors.length === 0, errors.slice(0, 3).join(' | '));

    // ── this page's identity is its own, not the home page's
    const meta = await page.evaluate(() => ({
      title: document.title,
      desc: document.querySelector('meta[name=description]')?.content || '',
      canonical: document.querySelector('link[rel=canonical]')?.href || '',
      ogImage: document.querySelector('meta[property="og:image"]')?.content || '',
      ogTitle: document.querySelector('meta[property="og:title"]')?.content || '',
      ogType: document.querySelector('meta[property="og:type"]')?.content || '',
      twImage: document.querySelector('meta[name="twitter:image"]')?.content || '',
      prev: document.querySelector('link[rel=prev]')?.href || '',
      next: document.querySelector('link[rel=next]')?.href || '',
      ld: document.querySelector('script[type="application/ld+json"]')?.textContent || '',
    }));
    r.ok(`i${n}: <title> names this issue`, meta.title.includes(`Issue #0${n}`), meta.title);
    r.ok(`i${n}: description is issue-specific`,
      meta.desc.includes(`Issue #0${n}`) && meta.desc.length > 80, meta.desc.slice(0, 70));
    r.ok(`i${n}: canonical points here`, meta.canonical.endsWith(`/read/issue-${n}`), meta.canonical);
    r.ok(`i${n}: og:image is this issue's cover`,
      meta.ogImage.endsWith(`cover-issue${n}.webp`), meta.ogImage);
    r.ok(`i${n}: twitter:image matches og:image`, meta.twImage === meta.ogImage);
    r.ok(`i${n}: og:title names this issue`, meta.ogTitle.includes(`#0${n}`), meta.ogTitle);
    r.ok(`i${n}: og:type is article`, meta.ogType === 'article', meta.ogType);
    r.ok(`i${n}: rel=prev`, n === 1 ? !meta.prev : meta.prev.endsWith(`issue-${n - 1}`), meta.prev);
    r.ok(`i${n}: rel=next`, n === 4 ? !meta.next : meta.next.endsWith(`issue-${n + 1}`), meta.next);

    let ld = null;
    try { ld = JSON.parse(meta.ld); } catch (e) { /* asserted next */ }
    r.ok(`i${n}: JSON-LD parses`, !!ld);
    if (ld) {
      const graph = ld['@graph'] || [];
      const issue = graph.find(g => g['@type'] === 'ComicIssue');
      const wp = graph.find(g => g['@type'] === 'WebPage');
      r.ok(`i${n}: has a ComicIssue node`, !!issue);
      r.ok(`i${n}: issueNumber is ${n}`, issue && issue.issueNumber === n, issue && String(issue.issueNumber));
      r.ok(`i${n}: has a publication date`,
        issue && /^\d{4}-\d{2}-\d{2}$/.test(issue.datePublished || ''), issue && issue.datePublished);
      r.ok(`i${n}: chapters are indexed`,
        issue && Array.isArray(issue.hasPart) && issue.hasPart.length >= 3,
        issue && String((issue.hasPart || []).length));
      r.ok(`i${n}: breadcrumb has three steps`, wp && wp.breadcrumb?.itemListElement?.length === 3);
      r.ok(`i${n}: declared part of the series`,
        issue && String(issue.isPartOf?.['@id'] || '').includes('#comicseries'));
    }

    // ── the story is actually on the page
    const dom = await page.evaluate(() => {
      const panel = document.querySelector('.issue-reader-panel');
      return {
        panels: document.querySelectorAll('.issue-reader-panel').length,
        panelId: panel?.id,
        active: !!panel?.classList.contains('active'),
        visible: panel ? getComputedStyle(panel).display !== 'none' : false,
        pages: document.querySelectorAll('.issue-reader-panel .reader-page').length,
        prose: document.querySelectorAll('.story-prose').length,
        tabs: document.querySelectorAll('.issue-page-tab').length,
        activeTab: document.querySelector('.issue-page-tab.active')?.textContent.trim(),
        crumbs: document.querySelectorAll('.issue-crumbs li').length,
        seq: document.querySelectorAll('.issue-seq-link').length,
        permalink: document.querySelectorAll('.reader-permalink').length,
      };
    });
    r.ok(`i${n}: exactly one reader panel`, dom.panels === 1, String(dom.panels));
    r.ok(`i${n}: it is panel-i${n}`, dom.panelId === `panel-i${n}`, dom.panelId);
    r.ok(`i${n}: panel is active and visible`, dom.active && dom.visible);
    r.ok(`i${n}: story pages rendered`, dom.pages >= 3, String(dom.pages));
    r.ok(`i${n}: prose rendered`, dom.prose >= 5, String(dom.prose));
    r.ok(`i${n}: four issues in the tab bar`, dom.tabs === 4, String(dom.tabs));
    r.ok(`i${n}: this issue's tab is current`, dom.activeTab === `Issue #0${n}`, dom.activeTab);
    r.ok(`i${n}: breadcrumb present`, dom.crumbs === 3, String(dom.crumbs));
    r.ok(`i${n}: prev/next present`, dom.seq === (n === 1 ? 1 : 2), String(dom.seq));
    r.ok(`i${n}: no link to the page you are on`, dom.permalink === 0, String(dom.permalink));

    // ── shared chrome survived the slice
    const chrome = await page.evaluate(() => ({
      nav: !!document.querySelector('nav .nav-links'),
      mobileNav: !!document.getElementById('mobileNav'),
      footer: !!document.querySelector('footer'),
      cmdk: !!document.getElementById('cmdk'),
      notes: !!document.getElementById('fnBar') && !!document.getElementById('fnDrawer'),
      kb: !!document.getElementById('kb-panel'),
      glPop: !!document.getElementById('glPop'),
      skip: document.querySelector('.skip-link')?.getAttribute('href'),
      navHashes: [...document.querySelectorAll('nav a[href^="#"]')].map(a => a.getAttribute('href')),
      issueLinks: [...document.querySelectorAll('footer a[href*="/read/issue-"]')].length,
    }));
    r.ok(`i${n}: nav present`, chrome.nav);
    r.ok(`i${n}: mobile nav present`, chrome.mobileNav);
    r.ok(`i${n}: footer present`, chrome.footer);
    r.ok(`i${n}: search palette present`, chrome.cmdk);
    r.ok(`i${n}: field notes present`, chrome.notes);
    r.ok(`i${n}: keyboard help present`, chrome.kb);
    r.ok(`i${n}: glossary popover present`, chrome.glPop);
    r.ok(`i${n}: skip link targets the story`, chrome.skip === '#read', chrome.skip);
    // Only #read is on this page; every other nav fragment must go home.
    r.ok(`i${n}: nav fragments retargeted home`,
      chrome.navHashes.every(h => h === '#read'), chrome.navHashes.join(','));
    r.ok(`i${n}: footer lists all four issues`, chrome.issueLinks === 4, String(chrome.issueLinks));

    // ── JS modules initialised against a one-panel DOM
    const js = await page.evaluate(() => ({
      flag: window.CATALYST_PAGE,
      search: typeof window.CatalystSearch?.open === 'function',
      notes: typeof window.CatalystFieldNotes?.open === 'function',
      trap: typeof window.CatalystFocusTrap?.anyOpen === 'function',
      jump: typeof window.catalystJumpTo === 'function',
    }));
    r.ok(`i${n}: recognised as issue page ${n}`,
      js.flag?.issuePage === true && js.flag?.issue === n, JSON.stringify(js.flag));
    r.ok(`i${n}: search module live`, js.search);
    r.ok(`i${n}: field notes module live`, js.notes);
    r.ok(`i${n}: focus trap live`, js.trap);
    r.ok(`i${n}: jump API live`, js.jump);

    // ── search still reaches the rest of the site from here
    await page.keyboard.press('Control+k');
    await page.waitForTimeout(350);
    r.ok(`i${n}: Ctrl/Cmd-K opens search`,
      await page.evaluate(() => document.getElementById('cmdk')?.classList.contains('open')) === true);
    await page.fill('#cmdkInput', 'heroes');
    await page.waitForTimeout(300);
    const homeHits = await page.evaluate(() =>
      [...document.querySelectorAll('.cmdk-row')].map(e => e.textContent).join(' | '));
    r.ok(`i${n}: home-page sections are searchable`, /Heroes/i.test(homeHits), homeHits.slice(0, 90));
    await page.fill('#cmdkInput', 'issue');
    await page.waitForTimeout(300);
    const issueHits = await page.evaluate(() =>
      [...document.querySelectorAll('.cmdk-row')].map(e => e.textContent.trim()));
    r.ok(`i${n}: sibling issues are searchable`,
      issueHits.some(t => /Issue #0[1-4]/.test(t)), issueHits.slice(0, 3).join(' | '));
    await page.keyboard.press('Escape');
    await page.close();
  }

  // ── moving between pages
  const page = await newPage(ctx);

  await page.goto(`${base}/read/issue-2`, { waitUntil: 'networkidle' });
  await page.click('.issue-page-tab:not(.active)');
  await page.waitForLoadState('networkidle');
  r.ok('tab bar navigates to another issue page', /issue-[134]/.test(page.url()), page.url());

  // A short deep link on the page it belongs to
  await page.goto(`${base}/read/issue-3#p2`, { waitUntil: 'networkidle' });
  await page.waitForFunction(() => {
    const ps = [...document.querySelectorAll('.issue-reader-panel .reader-page')];
    return ps.findIndex(p => getComputedStyle(p).display !== 'none') === 2;
  }, null, { timeout: 5000 }).catch(() => {});
  const onPage2 = await page.evaluate(() => {
    const ps = [...document.querySelectorAll('.issue-reader-panel .reader-page')];
    return ps.findIndex(p => getComputedStyle(p).display !== 'none');
  });
  r.ok('#p2 opens page 2 of that issue', onPage2 === 2, String(onPage2));

  // A shared link for a different issue must land on the right page, not break
  await page.goto(`${base}/read/issue-1#read-i4-p1`, { waitUntil: 'networkidle' });
  await page.waitForURL(/issue-4/, { timeout: 5000 }).catch(() => {});
  r.ok('a deep link for another issue redirects to it', /issue-4/.test(page.url()), page.url());

  await page.close();
  return r;
};
