#!/usr/bin/env python3
"""Derive issue.css — the subset of styles.css an issue page can actually use.

An issue page uses about 52 KB of the 290 KB stylesheet; the rest is rules for
sections that only exist on the home page. This writes the subset an issue
page could use, so those pages stop downloading the rest.

    python3 tools/split_css.py            # write issue.css
    python3 tools/split_css.py --check    # exit 1 if it is out of date
    python3 tools/split_css.py --report   # explain the split, write nothing

THE RULE, and why it is safe
----------------------------
A rule goes to home.css only when *every* selector in it names at least one
class or id that appears nowhere an issue page could produce it — not in any
of the four pages' markup, and not as a token in any string literal in
script.js (which is how classes get added at runtime). If a selector could
match, it stays in core.css. The test is deliberately over-inclusive about
what counts as live, so the failure mode is shipping a few bytes too many
rather than losing a style.

index.html is NOT touched: it keeps loading the whole of styles.css. That is
deliberate. Splitting it into two linked files was tried and measured, and it
changed the rendered home page — 1% of pixels at 1440px and 1,293px of height
at 390px — because lifting rules out of the middle of a stylesheet and
appending them at the end reorders the cascade for any equal-specificity
conflict. Deriving a filtered copy instead cannot have that problem: issue.css
keeps the original relative order and only omits rules that provably cannot
match, and styles.css itself is byte-for-byte unchanged.

The cost is that someone who visits both a home page and an issue page
downloads both sheets. That is the right trade here: the case worth optimising
is a shared link to an issue, which lands cold on an issue page.
"""

import argparse
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'styles.css')
OUT = os.path.join(ROOT, 'issue.css')

BANNER = """/* ═══════════════════════════════════════════════════════════════════
   ISSUE PAGES — /read/issue-1 … /read/issue-4

   Generated by tools/split_css.py from styles.css. Edit styles.css, not
   this file, then re-run the script; styles.css is the single source of
   truth and is what the home page still loads in full.

   This is styles.css with the rules removed that cannot match on an issue
   page — every selector in them names a class or id that appears neither
   in any issue page's markup nor in any string literal in script.js.
   Relative order is untouched, so the cascade here is the cascade there.
   ═══════════════════════════════════════════════════════════════════ */

"""


def live_tokens():
    """Classes and ids that could exist on an issue page."""
    live = set()
    for f in sorted(glob.glob(os.path.join(ROOT, 'read', '*.html'))):
        h = open(f, encoding='utf-8').read()
        for m in re.finditer(r'\bclass="([^"]+)"', h):
            live.update(m.group(1).split())
        live.update(re.findall(r'\bid="([A-Za-z][\w-]*)"', h))
    # Anything named in a JS string could be applied at runtime. Split each
    # literal into identifier-ish tokens so 'cmdk-row' and '.cmdk-row' both
    # register, and so a selector string like '.a .b' marks both.
    js = open(os.path.join(ROOT, 'script.js'), encoding='utf-8').read()
    for lit in re.findall(r"['\"`]([A-Za-z][\w .#:>()\[\]=-]{0,80})['\"`]", js):
        live.update(re.findall(r'[A-Za-z][\w-]*', lit))
    return live


def rules(css, start, end):
    """Yield (selector, rule_start, body_start, body_end, rule_end)."""
    i = start
    while i < end:
        if css.startswith('/*', i):
            nxt = css.find('*/', i)
            if nxt == -1:
                return
            i = nxt + 2
            continue
        brace = css.find('{', i)
        if brace == -1 or brace >= end:
            return
        sel = css[i:brace]
        depth, j = 1, brace + 1
        while j < end and depth:
            if css.startswith('/*', j):
                nxt = css.find('*/', j)
                if nxt == -1:
                    break
                j = nxt + 2
                continue
            if css[j] == '{':
                depth += 1
            elif css[j] == '}':
                depth -= 1
            j += 1
        yield sel.strip(), i, brace + 1, j - 1, j
        i = j


def is_home_only(selector, live):
    parts = [p.strip() for p in selector.split(',') if p.strip()]
    if not parts:
        return False
    for part in parts:
        tokens = re.findall(r'[.#]([A-Za-z][\w-]*)', part)
        if not tokens:
            return False           # bare element or * — could match anything
        if all(t in live for t in tokens):
            return False           # this selector could match; keep the rule
    return True


def split(css, live):
    """Return (core_text, home_text, stats)."""
    stats = {'home_rules': 0, 'core_rules': 0}

    def walk(a, b):
        core_parts, home_parts = [], []
        for sel, rs, bs, be, re_ in rules(css, a, b):
            chunk = css[rs:re_]
            if re.match(r'@(media|supports|container)\b', sel):
                inner_core, inner_home = walk(bs, be)
                head = css[rs:bs]
                if inner_home.strip():
                    home_parts.append(head + inner_home + '\n}\n')
                if inner_core.strip():
                    core_parts.append(head + inner_core + '\n}\n')
            elif sel.startswith('@'):
                core_parts.append(chunk)     # @font-face, @keyframes, @import
            elif is_home_only(sel, live):
                stats['home_rules'] += 1
                home_parts.append(chunk)
            else:
                stats['core_rules'] += 1
                core_parts.append(chunk)
        return ''.join(core_parts), ''.join(home_parts)

    core, home = walk(0, len(css))
    return core, home, stats


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--report', action='store_true')
    args = ap.parse_args()

    css = open(SRC, encoding='utf-8').read()
    live = live_tokens()
    core, home, stats = split(css, live)

    core_out = BANNER + core

    src_kb = len(css.encode()) / 1024
    out_kb = len(core_out.encode()) / 1024

    if args.report:
        print('styles.css   %7.1f KB  (%d rules kept + %d dropped) — home page'
              % (src_kb, stats['core_rules'], stats['home_rules']))
        print('issue.css    %7.1f KB  (%d rules) — the four issue pages'
              % (out_kb, stats['core_rules']))
        print('saved        %7.1f KB per issue-page load (%.0f%%)'
              % (src_kb - out_kb, 100 * (src_kb - out_kb) / src_kb))
        return 0

    if args.check:
        have = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else None
        if have != core_out:
            print('out of date, re-run tools/split_css.py: issue.css')
            return 1
        print('issue.css is up to date with styles.css')
        return 0

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(core_out)
    print('wrote issue.css  %7.1f KB  (was %.1f KB — %.1f KB saved per issue page)'
          % (out_kb, src_kb, src_kb - out_kb))
    return 0


if __name__ == '__main__':
    sys.exit(main())
